=====================================
Loaded image np.array of shape:  (1520, 128, 128, 3)
=====================================
=====================================
Splitted dataset in arrays of shape:  (1064, 128, 128, 3)  |  (456, 128, 128, 3)
=====================================
=====================================
Augmented splitted dataset in arrays of shape:  (1064, 128, 128, 3)  |  (456, 128, 128, 3)
=====================================
Traceback (most recent call last):
  File "/home/dofa/miniconda3/envs/test/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 162, in __getattr__
    return self.__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dofa/miniconda3/envs/test/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'epochs'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/dofa/Desktop/code/PMC/src/machine_learning/un_supervised/neural_network/train_single.py", line 201, in <module>
    build_and_train_model()
  File "/home/dofa/Desktop/code/PMC/src/machine_learning/un_supervised/neural_network/train_single.py", line 179, in build_and_train_model
    train(model, input_train_norm, input_train_aug_norm, input_test_norm, input_test_aug_norm, wandb.config.epochs, wandb.config.batch_size, callbacks)
                                                                                               ^^^^^^^^^^^^^^^^^^^
  File "/home/dofa/miniconda3/envs/test/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 164, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'epochs'